// /**
// * This code was generated by v0 by Vercel.
// * @see https://v0.dev/t/EBk50GeDh2O
// * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
// */

// /** Add fonts into your Next.js project:

// import { Inter } from 'next/font/google'

// inter({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import { TooltipProvider, Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip"
// import Link from "next/link"
// import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
// import { Button } from "@/components/ui/button"
// import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbSeparator, BreadcrumbPage } from "@/components/ui/breadcrumb"
// import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
// import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
// import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
// import { Separator } from "@/components/ui/separator"
// import { Gear, SignOut, UserCircle,  } from "@phosphor-icons/react"

// export function ProfilePage() {
//   return (
//         <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
//           <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-2">
//             <Card>
//               <CardHeader>
//                 <CardTitle>Profile</CardTitle>
//                 <CardDescription>View and update your profile information.</CardDescription>
//               </CardHeader>
//               <CardContent>
//                 <div className="grid gap-4">
//                   <div className="flex items-center gap-4">
//                     <Avatar className="h-16 w-16">
//                       <AvatarImage src="/placeholder-user.jpg" />
//                       <AvatarFallback>JD</AvatarFallback>
//                     </Avatar>
//                     <div className="grid gap-1">
//                       <div className="text-lg font-semibold">John Doe</div>
//                       <div className="text-sm text-muted-foreground">johndoe@example.com</div>
//                     </div>
//                   </div>
//                   <Separator />
//                   <div className="grid gap-2">
//                     <div className="flex items-center justify-between">
//                       <div className="text-muted-foreground">Username</div>
//                       <div>johndoe</div>
//                     </div>
//                     <div className="flex items-center justify-between">
//                       <div className="text-muted-foreground">Role</div>
//                       <div>Admin</div>
//                     </div>
//                     <div className="flex items-center justify-between">
//                       <div className="text-muted-foreground">Joined</div>
//                       <div>June 1, 2023</div>
//                     </div>
//                   </div>
//                   <Separator />
//                   <div className="grid gap-2">
//                     <div className="text-muted-foreground">About</div>
//                     <div>
//                       I am the admin of OptiWaste, a platform that helps businesses manage their waste and recycling.
//                     </div>
//                   </div>
//                   <div className="flex justify-end">
//                     <Button>Edit Profile</Button>
//                   </div>
//                 </div>
//               </CardContent>
//             </Card>
//             <Card>
//               <CardHeader>
//                 <CardTitle>Activity</CardTitle>
//                 <CardDescription>View your recent activity on the platform.</CardDescription>
//               </CardHeader>
//               <CardContent>
//                 <div className="grid gap-4">
//                   <div className="flex items-center justify-between">
//                     <div className="flex items-center gap-2">
//                       <ClipboardIcon className="h-5 w-5 text-muted-foreground" />
//                       <div>
//                         <div className="font-semibold">New Request</div>
//                         <div className="text-sm text-muted-foreground">
//                           A new waste collection request was submitted.
//                         </div>
//                       </div>
//                     </div>
//                     <div className="text-sm text-muted-foreground">2 hours ago</div>
//                   </div>
//                   <div className="flex items-center justify-between">
//                     <div className="flex items-center gap-2">
//                       <TruckIcon className="h-5 w-5 text-muted-foreground" />
//                       <div>
//                         <div className="font-semibold">Collector Assigned</div>
//                         <div className="text-sm text-muted-foreground">A collector was assigned to a request.</div>
//                       </div>
//                     </div>
//                     <div className="text-sm text-muted-foreground">1 day ago</div>
//                   </div>
//                   <div className="flex items-center justify-between">
//                     <div className="flex items-center gap-2">
//                       <DollarSignIcon className="h-5 w-5 text-muted-foreground" />
//                       <div>
//                         <div className="font-semibold">Payment Received</div>
//                         <div className="text-sm text-muted-foreground">A payment of $1,234.56 was received.</div>
//                       </div>
//                     </div>
//                     <div className="text-sm text-muted-foreground">3 days ago</div>
//                   </div>
//                   <div className="flex items-center justify-between">
//                     <div className="flex items-center gap-2">
//                       <SettingsIcon className="h-5 w-5 text-muted-foreground" />
//                       <div>
//                         <div className="font-semibold">Settings Updated</div>
//                         <div className="text-sm text-muted-foreground">Your account settings were updated.</div>
//                       </div>
//                     </div>
//                     <div className="text-sm text-muted-foreground">1 week ago</div>
//                   </div>
//                 </div>
//               </CardContent>
//             </Card>
//           </div>
//         </main>
//   );
// }






















