/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/12nJEH6sDNz
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import Image from "next/image";
import logo from "@/public/OPTIWASTE.png";
import { Trash } from "@phosphor-icons/react";

export default function RegistrationPage() {
  return (
    <div className="flex min-h-[100dvh]">
      <div className="hidden lg:block lg:w-1/2 bg-[url('/waste-truck.svg')] bg-cover bg-center" />
      <div className="flex flex-col justify-between w-full lg:w-1/2 p-6 md:p-10 lg:p-12 xl:p-16">
        <div className="flex items-center justify-between">
          <Image src={logo} alt="logo" />
          <div className="flex gap-2">
            <Link
              href="/login"
              className="inline-flex h-9 items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium text-foreground shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Sign In
            </Link>
            <Button>Sign Up</Button>
          </div>
        </div>
        <div className="flex flex-col items-start gap-6 mt-12">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Create your account</h1>
            <p className="text-muted-foreground md:text-xl">Get started with our platform today.</p>
          </div>
          <form className="w-full space-y-4">
            <div className="grid gap-2">
              <Input id="name" type="text" placeholder="John Doe" required />
            </div>
            <div className="grid gap-2">
              <Input id="email" type="email" placeholder="m@example.com" required />
            </div>
            <div className="grid gap-2">
              <Input id="password" type="password" required placeholder="password"/>
            </div>
            <div className="flex items-center gap-2">
              <Checkbox id="terms" required />
              <Label htmlFor="terms" className="text-sm text-muted-foreground">
                I agree to the{" "}
                <Link href="#" className="underline underline-offset-2" prefetch={false}>
                  terms and conditions
                </Link>
              </Label>
            </div>
            <Button  className="w-full">
             <Link href="/dashboard">Create Account</Link> 
            </Button>
          </form>
        </div>
        <div className="text-xs text-muted-foreground">&copy; 2024 OptiWaste. All rights reserved.</div>
      </div>
    </div>
  );
}
