/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ERrYhd924Nv
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"


export function LandingPage() {
  return (
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <section className="w-full py-12 md:py-24 lg:py-32 bg-background dark:bg-background-dark">
            <div className="container px-4 md:px-6">
              <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
                <div className="flex flex-col justify-center space-y-4">
                  <div className="space-y-2">
                    <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                      Welcome to OptiWaste
                    </h1>
                    <p className="max-w-[600px] text-muted-foreground md:text-xl">
                      OptiWaste is a waste collection platform that helps you manage your waste more efficiently. We
                      offer a range of services to help you reduce, reuse, and recycle your waste.
                    </p>
                  </div>
                  <div className="flex flex-col gap-2 min-[400px]:flex-row">
                    <Link
                      href="/signup"
                      className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      Get Started
                    </Link>
                    <Link
                      href="/login"
                      className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}
                    >
                      Sign In
                    </Link>
                  </div>
                </div>
                {/* <img
                  src="/placeholder.svg"
                  width="550"
                  height="550"
                  alt="Hero"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
                /> */}
              </div>
            </div>
          </section>
          <section className="w-full py-12 md:py-24 lg:py-32 bg-muted dark:bg-muted-dark">
            <div className="container px-4 md:px-6">
              <div className="flex flex-col items-center justify-center space-y-4 text-center">
                <div className="space-y-2">
                  <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm dark:bg-muted-dark dark:text-muted-foreground-dark">
                    Our Services
                  </div>
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Waste Collection and Recycling</h2>
                  <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-muted-foreground-dark">
                    OptiWaste offers a range of services to help you manage your waste more efficiently. We provide
                    waste collection, recycling, and disposal services to both residential an
                  </p>
                </div>
              </div>
            </div>
          </section>
        </main>
  )
}
