/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RbnYbFd3r74
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export default function LoginPage() {
  return (
    (<div className="flex min-h-screen">
      <div className="w-1/2">
        <img
          src="/placeholder.svg"
          alt="Garbage truck"
          className="object-cover w-full h-full" />
      </div>
      <div className="flex flex-col items-center justify-center w-1/2 p-8">
        <div className="flex flex-col items-center mb-8">
          <TrashIcon className="w-12 h-12 mb-4" />
          <h1 className="text-4xl font-bold">OPTIWASTE</h1>
          <p className="text-sm text-muted-foreground">ESTD 2024</p>
        </div>
        <form className="w-full max-w-sm space-y-4">
          <div>
            <label htmlFor="email" className="sr-only">
              E-mail
            </label>
            <Input id="email" type="email" placeholder="E-mail" />
          </div>
          <div>
            <label htmlFor="password" className="sr-only">
              Enter your password
            </label>
            <Input id="password" type="password" placeholder="Enter your password" />
          </div>
          <Button className="w-full" variant="default">
            Sign In
          </Button>
        </form>
        <div className="mt-4 text-center">
          <p className="text-sm">
            Don't have an account?{" "}
            <a href="#" className="underline">
              Register
            </a>
          </p>
        </div>
        <Button
          variant="outline"
          className="mt-4 w-full flex items-center justify-center">
          <ChromeIcon className="w-4 h-4 mr-2" />
          REGISTER WITH GOOGLE
        </Button>
      </div>
    </div>)
  );
}

function ChromeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}
