/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/08xXlwiXLPM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { TooltipProvider, Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip"
import Link from "next/link"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"
import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink } from "@/components/ui/breadcrumb"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"

export function PaymentPage() {
  return (
        <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <Card>
              <CardHeader>
                <CardTitle>Total Payments</CardTitle>
                <CardDescription>The total amount of payments received.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="text-4xl font-bold">$125,345</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Pending Payments</CardTitle>
                <CardDescription>The number of payments that are still pending.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="text-4xl font-bold">12</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Successful Payments</CardTitle>
                <CardDescription>The number of payments that have been successfully processed.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="text-4xl font-bold">1,234</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Failed Payments</CardTitle>
                <CardDescription>The number of payments that have failed to process.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="text-4xl font-bold">32</div>
              </CardContent>
            </Card>
          </div>
          <Card>
            <CardHeader>
              <CardTitle>Payment History</CardTitle>
              <CardDescription>View all payments made to the system.</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Date</TableHead>
                    <TableHead>Amount</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Method</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>2023-06-01</TableCell>
                    <TableCell>$250.00</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Successful</Badge>
                    </TableCell>
                    <TableCell>Credit Card</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>2023-05-15</TableCell>
                    <TableCell>$150.00</TableCell>
                    <TableCell>
                      <Badge variant="outline">Pending</Badge>
                    </TableCell>
                    <TableCell>PayPal</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>2023-04-30</TableCell>
                    <TableCell>$350.00</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Successful</Badge>
                    </TableCell>
                    <TableCell>Bank Transfer</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>2023-04-20</TableCell>
                    <TableCell>$450.00</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Successful</Badge>
                    </TableCell>
                    <TableCell>Credit Card</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>2023-04-10</TableCell>
                    <TableCell>$550.00</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Successful</Badge>
                    </TableCell>
                    <TableCell>PayPal</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </main>
  );
}








