/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Hjsiurghcm8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Drawer, DrawerTrigger, DrawerContent, DrawerHeader, DrawerTitle, DrawerDescription, DrawerFooter, DrawerClose } from "@/components/ui/drawer"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"

export function RequestDetails() {
  return (
    <div className="w-full max-w-4xl mx-auto py-12 md:py-16 lg:py-20">
      <div className="px-4 md:px-6 lg:px-8">
        <div className="text-center space-y-4">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Request Waste Collection</h1>
          <p className="text-muted-foreground md:text-xl">
            Fill out the form below to schedule a waste pickup at your location.
          </p>
        </div>
        <form className="mt-8 space-y-6">
          <div>
            <Label htmlFor="location">Location</Label>
            <div className="flex items-center gap-2">
              <Input id="location" type="text" placeholder="Enter your address" className="flex-1" />
              <Drawer>
            <DrawerTrigger asChild>
              <Button variant="outline">
                <div className="h-5 w-5" />
                Select on Map
              </Button>
            </DrawerTrigger>
            <DrawerContent>
              <DrawerHeader>
                <DrawerTitle>Select Location</DrawerTitle>
                <DrawerDescription>Choose a location on the map for your waste pickup.</DrawerDescription>
              </DrawerHeader>
              <div className="flex-1">
                <div className="h-[400px]" />
              </div>
              <DrawerFooter>
                <Button>Confirm Location</Button>
                <DrawerClose asChild>
                  <Button variant="outline">Cancel</Button>
                </DrawerClose>
              </DrawerFooter>
            </DrawerContent>
          </Drawer>
            </div>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <Label htmlFor="waste-type">Waste Type</Label>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Select waste type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="general">General Waste</SelectItem>
                  <SelectItem value="recycling">Recycling</SelectItem>
                  <SelectItem value="organic">Organic Waste</SelectItem>
                  <SelectItem value="hazardous">Hazardous Waste</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label htmlFor="quantity">Quantity</Label>
              <Input id="quantity" type="number" placeholder="Enter quantity" />
            </div>
          </div>
          <div>
            <Label htmlFor="instructions">Special Instructions</Label>
            <Textarea id="instructions" rows={3} placeholder="Enter any special instructions" />
          </div>
          <div className="flex justify-end">
            <Button type="submit">Next</Button>
          </div>
        </form>
      </div>
    </div>
  )
}
