/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lE0qbCbzhxh
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these Font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Drawer, DrawerTrigger, DrawerContent, DrawerHeader, DrawerTitle, DrawerFooter } from "@/components/ui/drawer"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { X, Check, CircleDashed } from "lucide-react"


export function RequestHistory() {
  return (
    <div className="w-full max-w-4xl mx-auto py-12 md:py-16 lg:py-20">
      <div className="px-4 md:px-6 lg:px-8">
        <div className="text-center space-y-4">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">All Waste Collection Requests</h1>
          <p className="text-muted-foreground md:text-xl">View and manage all your waste collection requests.</p>
        </div>
        <div className="mt-8 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Requests</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <div className="bg-muted rounded-lg p-4 cursor-pointer hover:bg-muted/50 transition-colors">
                  <div className="font-medium">Request #1</div>
                  <div className="text-muted-foreground">June 15, 2023</div>
                  <div className="text-green-500 font-medium mt-2">
                  <Check className="w-4 h-4 inline-block mr-1" />
                    Scheduled</div>
                  <Drawer>
                    <DrawerTrigger asChild>
                      <Button variant="link" className="mt-4 text-sm underline">
                        View Details
                      </Button>
                    </DrawerTrigger>
                    <DrawerContent>
                    <div className="mx-auto w-full max-w-sm">
                      <DrawerHeader>
                        <DrawerTitle>Request #1 Details</DrawerTitle>
                      </DrawerHeader>
                      <div className="px-4 py-6 space-y-4">
                        <div>
                          <div className="font-medium">Location</div>
                          <div>123 Main St, Anytown USA</div>
                        </div>
                        <Separator className="my-4" />
                        <div>
                          <div className="font-medium">Waste Type</div>
                          <div>General Waste</div>
                        </div>
                        <Separator className="my-4" />
                        <div>
                          <div className="font-medium">Quantity</div>
                          <div>3 bags</div>
                        </div>
                        <Separator className="my-4" />
                        <div>
                          <div className="font-medium">Special Instructions</div>
                          <div>Please leave the bags by the side door.</div>
                        </div>
                        <Separator className="my-4" />
                        <div className="flex items-center justify-between">
                          <div className="font-medium">Status</div>
                          <div className="text-green-500 font-medium">
                            <Check className="w-4 h-4 inline-block mr-1" />
                            Scheduled</div>
                        </div>
                        <Separator className="my-4" />
                        <div className="flex items-center justify-between">
                          <div className="font-medium">Scheduled Pickup</div>
                          <div>June 15, 2023</div>
                        </div>
                        <DrawerFooter>
                          <Button variant="outline">Cancel Request</Button>
                          <Button>Make Payment</Button>
                        </DrawerFooter>
                      </div>
                      </div>
                    </DrawerContent>
                  </Drawer>
                </div>
                <div className="bg-muted rounded-lg p-4 cursor-pointer hover:bg-muted/50 transition-colors">
                  <div className="font-medium">Request #2</div>
                  <div className="text-muted-foreground">May 30, 2023</div>
                  <div className="text-yellow-500 font-medium mt-2">
                  <CircleDashed className="w-4 h-4 inline-block mr-1" />
                    Pending</div>
                  <Drawer>
                    <DrawerTrigger asChild>
                      <Button variant="link" className="mt-4 text-sm underline">
                        View Details
                      </Button>
                    </DrawerTrigger>
                    <DrawerContent>
                    <div className="mx-auto w-full max-w-sm">
                      <DrawerHeader>
                        <DrawerTitle>Request #2 Details</DrawerTitle>
                      </DrawerHeader>
                      <div className="px-4 py-6 space-y-4">
                        <div>
                          <div className="font-medium">Location</div>
                          <div>456 Oak St, Anytown USA</div>
                        </div>
                        <Separator className="my-4" />
                        <div>
                          <div className="font-medium">Waste Type</div>
                          <div>Recyclables</div>
                        </div>
                        <Separator className="my-4" />
                        <div>
                          <div className="font-medium">Quantity</div>
                          <div>2 bags</div>
                        </div>
                        <Separator className="my-4" />
                        <div>
                          <div className="font-medium">Special Instructions</div>
                          <div>Please pick up early in the morning.</div>
                        </div>
                        <Separator className="my-4" />
                        <div className="flex items-center justify-between">
                          <div className="font-medium">Status</div>
                          <div className="text-yellow-500 font-medium">
                          <CircleDashed className="w-4 h-4 inline-block mr-1" />
                            Pending</div>
                        </div>
                        <Separator className="my-4" />
                        <div className="flex items-center justify-between">
                          <div className="font-medium">Scheduled Pickup</div>
                          <div>June 1, 2023</div>
                        </div>
                        <DrawerFooter>
                          <Button variant="outline">Cancel Request</Button>
                          <Button>Make Payment</Button>
                        </DrawerFooter>
                      </div>
                      </div>
                    </DrawerContent>
                  </Drawer>
                </div>
                <div className="bg-muted rounded-lg p-4 cursor-pointer hover:bg-muted/50 transition-colors">
                  <div className="font-medium">Request #3</div>
                  <div className="text-muted-foreground">April 20, 2023</div>
                  <div className="text-red-500 font-medium mt-2">
                    <X className="w-4 h-4 inline-block mr-1" />
                    Cancelled</div>
                  <Drawer>
                    <DrawerTrigger asChild>
                      <Button variant="link" className="mt-4 text-sm underline">
                        View Details
                      </Button>
                    </DrawerTrigger>
                    <DrawerContent>
                      <div className="mx-auto w-full max-w-sm">
                        <DrawerHeader>
                          <DrawerTitle className="font-bold">Request #3 Details</DrawerTitle>
                        </DrawerHeader>
                        <div className="p-4 pb-0">
                          <div>
                            <div className="font-bold">Location</div>
                            <div>789 Elm St, Anytown USA</div>
                          </div>
                          <Separator className="my-4" />
                          <div>
                            <div className="font-bold">Waste Type</div>
                            <div>Bulky Waste</div>
                          </div>
                          <Separator className="my-4" />
                          <div>
                            <div className="font-bold">Quantity</div>
                            <div>1 item</div>
                          </div>
                          <Separator className="my-4" />
                          <div>
                            <div className="font-bold">Special Instructions</div>
                            <div>Please pick up from the front porch.</div>
                          </div>
                          <Separator className="my-4" />
                          <div className="flex items-center justify-between">
                            <div className="font-bold">Status</div>
                            <div className="text-red-500 font-medium">
                            <X className="w-4 h-4 inline-block mr-1" />
                              Cancelled</div>
                          </div>
                          <Separator className="my-4" />
                          <div className="flex items-center justify-between">
                            <div className="font-bold">Scheduled Pickup</div>
                            <div>April 22, 2023</div>
                          </div>
                          <DrawerFooter>
                            <Button variant="outline">Cancel Request</Button>
                            <Button>Make Payment</Button>
                          </DrawerFooter>
                        </div>
                      </div>
                    </DrawerContent>
                  </Drawer>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
